### ISSUE TITLE
Integrating types to make this work with TypeScript

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/gossipsub-js#4]
I brought up TypeScript support in the Libp2p Roadmap document. Raul supports having TypeScript declarations for js-libp2p. I created a [repo](https://github.com/ChainSafeSystems/ts-libp2p-types) for this purpose and also found this [other repo](https://github.com/polkadot-js/ts/blob/master/types/libp2p/index.d.ts) as well. The end goal would be to merge it into js-libp2p, just like we want to do with this library.

In either case, these will need to be integrated into this repo.

Any thoughts?

cc @GregTheGreek, @ansermino

**Comment by GregTheGreek** [comment]
Whats the status on this? Should we wait until we chat with the libp2p2 team?

**Comment by Mikerah** [comment]
I think we should wait until the chat with the libp2p team. I will contact Raul again to see what their availability is on their end.

**Comment by Mikerah** [comment]
During the call, there were several ideas about how to go about this. For now, we will be making bindings for gossipsub and potentially in the future, make them for libp2p.

**Comment by Mikerah** [comment]
If we type the element using `any` or `object`, I think that defeats the purpose of using types and we don't get the "built-in" documentation that using TypeScript provides. By locally typing elements, do you mean something like [this](https://github.com/polkadot-js/ts/blob/master/types/libp2p-crypto/index.d.ts)?

**Comment by raulk** [comment]
That's an interesting approach that's [enabled by typeRoots](https://github.com/polkadot-js/ts/blob/master/tsconfig.json#L5). That could definitely work -- and in fact we can go over those types at the Polkadot repo and revise them in order to, eventually, add them to the corresponding repos at libp2p.

What I had in mind was something like this. Imagine an `index.d.ts` file in this repo's root:

```ts
interface libp2pswitch {
  // lazily declare only the methods and fields you use.
  methodA(): typeA;
  methodB(): typeB;
  readonly fieldC: typeC;
}

class GossipSub {
  static public readonly switch: libp2pswitch;
  subscribe(topic: string): Result;
}
```

But yeah, I agree that placing the ambient declarations for each imported module in a file of its own, and linking it via typeRoots is probably cleaner and better scoped.

On a related note, let's try and converge our types with Polkadot's!

**Comment by GregTheGreek** [comment]
Closing since its stale
